site_name: Obsidian Analyzer
nav:
  - Home: docs/index.md
  - Getting Started: getting_started.md
  - Architecture: DOCS_architecture.md
  - Commands: DOCS_just_commands.md
  - CI/CD: DOCS_cicd.md
  - Local Setup: DOCS_running_locally.md
  - Requirements: DOCS_requirements.md
  - Testing: DOCS_tests.md
  - API: api_reference.md
  - Development: development.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your/repo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "google"
            show_root_heading: true
            show_root_full_path: false
  - autorefs:
      link_titles: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
